export const IngredientsActionTypes = {
    GET_INGREDIENTS:'GET_INGREDIENTS',
    CREATE_INGREDIENT: 'CREATE_INGREDIENT',
    DELETE_INGREDIENT: 'DELETE_INGREDIENT',
    UPDATE_INGREDIENT: 'UPDATE_INGREDIENT'
};